"""empty message

Revision ID: a26c667a54e9
Revises: 
Create Date: 2024-07-05 21:08:33.284498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26c667a54e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dividend', sa.Integer(), nullable=False),
    sa.Column('divisor', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computation')
    # ### end Alembic commands ###
