"""empty message

Revision ID: b4f3da7ec8c9
Revises: a26c667a54e9
Create Date: 2024-07-05 21:10:35.541608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f3da7ec8c9'
down_revision = 'a26c667a54e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computation', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computation', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
